# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05f04d81f7b7bca790b538c5512fe095d17ecf6812c1d245b65e770682b1c3271df48b249b38ea106befb124ba97155826ff67f005c93aa1bd27292968d85ab2

test:
  secret_key_base: 37f2d80298e4281bd50a75f808276e75c64bd8cc50be640ab48d127ae0c2b760bca6ee0d77803c8c275c8f6c23b07bfec09d1ef81bc51fa37bbdd07c7bc81302

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
